# For github pages
publishDir = "docs"

#baseURL = "http://example.org/"
baseURL = "https://barakinio.github.io/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Barak Shefer"

# language code ["en"]
languageCode = "en"
# language name ["English"]
languageName = "English"


# Author config
[author]
  name = "Barak Shefer"
  email = "barakshfr@gmail.com"
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "resume"
    pre = ""
    post = ""
    name = "Resume"
    url = "/resume/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    url = "https://github.com/barakinio"
  [[menu.main]]
    weight = 5
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-fw'></i>"
    url = "https://www.linkedin.com/in/barak-shefer/"
  [[menu.main]]
    weight = 6
    identifier = "twitter"
    pre = "<i class='fab fa-twitter fa-fw'></i>"
    url = "https://twitter.com/Barakinio"


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params.home]
    [params.home.profile]
        social = false